#%RAML 1.0 NamedExample
{
    "id": null,
    "items": [
        {
            "exception": null,
            "message": null,
            "payload": {
                "success": true,
                "id": "001aj00000BrQ1LAAV",
                "errors": []
            },
            "id": "001aj00000BrQ1LAAV",
            "successful": true,
            "statusCode": null
        }
    ],
    "successful": true
}