#%RAML 1.0 NamedExample
{
  "status": "OK",
  "apiName": "salesforce-sys-api",
  "apiVersion": "1.0.0",
  "timestamp": "2024-03-01T13:15:25.000Z",
  "dependencies": [
    {
      "name": "Salesforce",
      "status": "UP"
    }
  ]
}
